export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';