// category
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const RESTORE_CATEGORY_SUCCESS = 'RESTORE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';

// brand
export const GET_BRANDS = 'GET_BRANDS';
export const ADD_BRAND_SUCCESS = 'ADD_BRAND_SUCCESS';
export const UPDATE_BRAND_SUCCESS = 'UPDATE_BRAND_SUCCESS';
export const RESTORE_BRAND_SUCCESS = 'RESTORE_BRAND_SUCCESS';
export const DELETE_BRAND_SUCCESS = 'DELETE_BRAND_SUCCESS';

// loading
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

// authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';